dist: xenial
language: go
go:
  - 1.11.x
script:
  - make build-ci
addons:
  ssh_known_hosts: '$DEPLOY_HOST'
before_deploy:
  - openssl aes-256-cbc -K $encrypted_5304021bf379_key -iv $encrypted_5304021bf379_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avn --delete $TRAVIS_BUILD_DIR/dist/freebsd-amd64/ $SSH_USER@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master
